= ERC-20

ERC-20 token 合约跟踪 xref:tokens.adoc#different-kinds-of-tokens[*同质化* token]：任何一个 token 与任何其他 token 完全相等；没有 token 具有与其相关的特殊权利或行为。这使得 ERC-20 token 可用于*交换媒介货币*、*投票权*、*质押*等。

OpenZeppelin Contracts 提供了许多与 ERC20 相关的合约。在 xref:api:token/ERC20.adoc[`API 参考`] 中，你将找到有关其属性和用法的详细信息。

[[constructing-an-erc20-token-contract]]
== 构建 ERC-20 Token 合约

使用 Contracts，我们可以轻松创建我们自己的 ERC-20 token 合约，该合约将用于跟踪 _Gold_ (GLD)，这是一款假设游戏中的内部货币。

这是我们的 GLD token 可能的样子。

[source,solidity]
----
include::api:example$token/ERC20/GLDToken.sol[]
----

我们的合约通常通过 https://solidity.readthedocs.io/en/latest/contracts.html#inheritance[继承] 使用，在这里我们重用 xref:api:token/ERC20.adoc#erc20[`ERC20`] 用于基本标准实现以及 xref:api:token/ERC20.adoc#ERC20-name--[`name`]、xref:api:token/ERC20.adoc#ERC20-symbol--[`symbol`] 和 xref:api:token/ERC20.adoc#ERC20-decimals--[`decimals`] 可选扩展。此外，我们正在创建一个 `initialSupply` 的 token，它将被分配给部署合约的地址。

提示：有关 ERC-20 供应机制的更完整讨论，请参阅 xref:erc20-supply.adoc[创建 ERC-20 供应]。

就是这样！部署后，我们将能够查询部署者的余额：

[source,javascript]
----
> GLDToken.balanceOf(deployerAddress)
1000000000000000000000
----

我们还可以将这些 token xref:api:token/ERC20.adoc#IERC20-transfer-address-uint256-[转移] 到其他帐户：

[source,javascript]
----
> GLDToken.transfer(otherAddress, 300000000000000000000)
> GLDToken.balanceOf(otherAddress)
300000000000000000000
> GLDToken.balanceOf(deployerAddress)
700000000000000000000
----

[[a-note-on-decimals]]
== 关于 `decimals` 的注意事项

通常，你可能希望能够将你的 token 分成任意数量：例如，如果你拥有 `5 GLD`，你可能想将 `1.5 GLD` 发送给朋友，并将 `3.5 GLD` 留给自己。不幸的是，Solidity 和 EVM 不支持此行为：只能使用整数（整个）数字，这构成了一个问题。你可以发送 `1` 或 `2` 个 token，但不能发送 `1.5` 个。

为了解决这个问题，xref:api:token/ERC20.adoc#ERC20[`ERC20`] 提供了一个 xref:api:token/ERC20.adoc#ERC20-decimals--[`decimals`] 字段，用于指定 token 有多少位小数。为了能够转移 `1.5 GLD`，`decimals` 必须至少为 `1`，因为该数字有一位小数。

如何实现这一目标？实际上非常简单：token 合约可以使用更大的整数值，因此 `50` 的余额将代表 `5 GLD`，`15` 的转移将对应于发送 `1.5 GLD`，依此类推。

重要的是要理解 `decimals` *仅用于显示目的*。合约内部的所有算术仍然在整数上执行，并且必须由不同的用户界面（钱包、交易所等）根据 `decimals` 调整显示的值。每个帐户的 token 总供应量和余额未在 `GLD` 中指定：你需要除以 `10 ** decimals` 才能获得实际的 `GLD` 金额。

你可能想使用 `18` 的 `decimals` 值，就像 Ether 和大多数正在使用的 ERC-20 token 合约一样，除非你有非常特殊的原因不这样做。在铸造 token 或转移它们时，你实际上会发送数字 `num GLD * (10 ** decimals)`。

注意：默认情况下，`ERC20` 使用 `18` 作为 `decimals` 的值。要使用不同的值，你需要覆盖合约中的 `decimals()` 函数。

```solidity
function decimals() public view virtual override returns (uint8) {
  return 16;
}
```

因此，如果你想使用具有 18 位小数的 token 合约发送 `5` 个 token，则实际调用的方法是：

```solidity
transfer(recipient, 5 * (10 ** 18));
```