= 代币

啊，"代币"：区块链最强大也是最容易被误解的工具。

代币是_区块链中某事物的表示形式_。这个事物可以是金钱、时间、服务、公司股份、虚拟宠物，任何东西。通过将事物表示为代币，我们可以允许智能合约与它们交互、交换它们、创建或销毁它们。

[[but_first_coffee_a_primer_on_token_contracts]]
== 首先，[strikethrough]#咖啡# 代币合约入门

围绕代币的许多困惑来自于两个概念的混淆：_代币合约_和实际的_代币_。

_代币合约_ 仅仅是一个 Ethereum 智能合约。"发送代币" 实际上意味着 "调用某人编写和部署的智能合约上的一个方法"。归根结底，代币合约只不过是地址到余额的映射，加上一些增加和减少这些余额的方法。

正是这些余额代表了_代币_本身。当某人在代币合约中的余额非零时，他们就 "拥有代币"。就是这样！这些余额可以被认为是金钱、游戏中的经验值、所有权契据或投票权，并且这些代币中的每一个都将存储在不同的代币合约中。

[[different-kinds-of-tokens]]
== 不同类型的代币

请注意，拥有两张选票和两份所有权契据之间存在很大差异：每张选票与其他所有选票相同，但房屋通常不是！这被称为 https://en.wikipedia.org/wiki/Fungibility[可替代性]。 _可替代商品_ 是等价且可互换的，例如 Ether、法定货币和投票权。 _不可替代商品_ 是独一无二且截然不同的，例如所有权契据或收藏品。

简而言之，在处理不可替代品（例如你的房子）时，你在乎你拥有_哪些_，而在处理可替代资产（例如你的银行对账单）时，重要的是你拥有_多少_。

== 标准

即使代币的概念很简单，但它们的实现方式却多种多样。因为 Ethereum 中的一切都只是一个智能合约，并且没有关于智能合约必须做什么的规则，所以社区开发了各种*标准*（称为 EIP 或 ERC），用于记录合约如何与其他合约互操作。

你可能听说过 ERC-20 或 ERC-721 代币标准，这就是你来这里的原因。请访问我们的专门指南以了解更多信息：

 * xref:erc20.adoc[ERC-20]：最广泛使用的可替代资产代币标准，尽管其简单性有些限制。
 * xref:erc721.adoc[ERC-721]：不可替代代币的事实上的解决方案，通常用于收藏品和游戏。
 * xref:erc1155.adoc[ERC-1155]：一种新颖的多代币标准，允许单个合约表示多个可替代和不可替代代币，以及用于提高 Gas 效率的批量操作。
