= 升级使用

如果你的合约将要通过可升级性进行部署，例如使用 xref:upgrades-plugins::index.adoc[OpenZeppelin Upgrades Plugins]，那么你需要使用 OpenZeppelin Contracts 的可升级变体。

这个变体版本以一个单独的包 `@openzeppelin/contracts-upgradeable` 提供，它托管在 https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable[OpenZeppelin/openzeppelin-contracts-upgradeable] 仓库中。它使用 `@openzeppelin/contracts` 作为 peer dependency。

它遵循 xref:upgrades-plugins::writing-upgradeable.adoc[编写可升级合约] 的所有规则：构造函数被初始化函数替代，状态变量在初始化函数中初始化，并且我们还会检查跨小版本之间的存储不兼容性。

提示：OpenZeppelin 提供了一整套用于部署和保护可升级智能合约的工具。xref:openzeppelin::upgrades.adoc[查看完整的资源列表]。

== 概述

=== 安装

```console
$ npm install @openzeppelin/contracts-upgradeable @openzeppelin/contracts
```

=== 用法

Upgradeable 包复制了主 OpenZeppelin Contracts 包的结构，但是每个文件和合约都有后缀 `Upgradeable`。

```diff
-import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
+import {ERC721Upgradeable} from "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";
 
-contract MyCollectible is ERC721 {
+contract MyCollectible is ERC721Upgradeable {
```

注意：接口和库不包含在 Upgradeable 包中，而是从主 OpenZeppelin Contracts 包中导入。

构造函数被内部初始化函数替代，遵循命名约定 `+__{ContractName}_init+`。由于这些是内部函数，你必须始终定义你自己的 public 初始化函数，并调用你所继承的合约的父初始化函数。

```diff
-    constructor() ERC721("MyCollectible", "MCO") public {
+    function initialize() initializer public {
+        __ERC721_init("MyCollectible", "MCO");
     }
```

注意：与多重继承一起使用需要特别注意。请参阅下面标题为 <<multiple-inheritance>> 的部分。

一旦这个合约设置并编译好，你可以使用 xref:upgrades-plugins::index.adoc[Upgrades Plugins] 部署它。下面的代码片段展示了一个使用 Hardhat 的部署脚本示例。

```js
// scripts/deploy-my-collectible.js
const { ethers, upgrades } = require("hardhat");

async function main() {
  const MyCollectible = await ethers.getContractFactory("MyCollectible");

  const mc = await upgrades.deployProxy(MyCollectible);

  await mc.waitForDeployment();
  console.log("MyCollectible deployed to:", await mc.getAddress());
}

main();
```

== 更多注意事项

[[multiple-inheritance]]
=== 多重继承

初始化函数不会像构造函数一样被编译器线性化。因此，每个 `+__{ContractName}_init+` 函数嵌入了对所有父初始化函数的线性化调用。因此，调用其中两个 `init` 函数可能会多次初始化同一个合约。

在每个合约中找到的函数 `+__{ContractName}_init_unchained+` 是初始化函数减去对父初始化函数的调用，可用于避免重复初始化问题，但不建议手动执行此操作。我们希望能够在未来版本的 Upgrades Plugins 中为此实现安全检查。

=== 命名空间存储

你可能会注意到，合约使用带有 `@custom:storage-location erc7201:<NAMESPACE_ID>` 注释的结构体来存储合约的状态变量。这遵循 https://eips.ethereum.org/EIPS/eip-7201[ERC-7201: 命名空间存储布局] 模式，其中每个合约在与其继承链中的其他合约分离的命名空间中都有自己的存储布局。

如果没有命名空间存储，简单地添加一个状态变量是不安全的，因为它会“向下移动”继承链中下面的所有状态变量。这使得存储布局不兼容，如 xref:upgrades-plugins::writing-upgradeable.adoc#modifying-your-contracts[编写可升级合约] 中所述。

Upgradeable 包中使用的命名空间存储模式允许我们在未来自由添加新的状态变量，而不会损害与现有部署的存储兼容性。它还允许更改继承顺序，而不会对生成的存储布局产生影响，只要所有继承的合约都使用命名空间存储。
